---
roles:
  - name: robertdebock.bootstrap
  # - name: robertdebock.buildtools
  - name: robertdebock.ca_certificates
  # - name: robertdebock.openssl
  # - name: robertdebock.python_pip
  - name: robertdebock.users
# collections:
#   - name: community.crypto
