---
- name: prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.ca_certificates
    - role: robertdebock.users
      users_group_list:
        - name: cool
      users_user_list:
        - name: cool
          group: cool
          home: /opt/cool
          shell: /usr/sbin/nologin
          system: yes
