---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.ca_certificates
    - role: robertdebock.users
      users_groups:
        - name: cool
      users:
        - name: cool
          group: cool
          home: /opt/cool
          shell: /usr/sbin/nologin
          system: true
