---
- name: Verify
  hosts: all
  become: no
  gather_facts: no

  tasks:
    - name: check if port 9980 is open
      ansible.builtin.wait_for:
        port: 9980

    - name: check if "OK" is returned from https://localhost:9980
      ansible.builtin.uri:
        url: "https://127.0.0.1:9980"
        return_content: yes
        validate_certs: no
      register: collabora_online_test_one
      failed_when: "'OK' not in collabora_online_test_one.content"

    - name: check if hosting/discovery is available on https://localhost:9980
      ansible.builtin.uri:
        url: "https://127.0.0.1:9980/hosting/discovery"
        return_content: yes
        validate_certs: no
      register: collabora_online_test_two
