---
- name: Verify
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: Check if port 9980 is open
      ansible.builtin.wait_for:
        port: 9980

    - name: Access web url
      block:
        - name: "check if 'OK' is returned from https://localhost:9980"
          ansible.builtin.uri:
            url: "http://127.0.0.1:9980"
            return_content: true
            validate_certs: false
          register: collabora_online_test_one
          failed_when: "'OK' not in collabora_online_test_one.content"
      rescue:
        - name: Show registered variable
          ansible.builtin.debug:
            msg: "collabora_online_test_one: {{ collabora_online_test_one }}"

    - name: "check if hosting/discovery is available on https://localhost:9980"
      ansible.builtin.uri:
        url: "http://127.0.0.1:9980/hosting/discovery"
        return_content: true
        validate_certs: false

    - name: "check if admin.html is available on https://localhost:9980"
      ansible.builtin.uri:
        url: "http://127.0.0.1:9980/browser/dist/admin/admin.html"
        return_content: true
        validate_certs: false
        status_code:
          - 401
